### ISSUE TITLE
Install fails if existing app has conflicting table name

### ISSUE THREAD

**Issue by erm213** [rubysherpas/forem#622] opened 2014-11-23 02:01 UTC
I have an existing Rails 4 app. I followed the install instructions in the README.md

I have a subscriptions table. When I try to install forem, it fails, as it too has a subscriptions table. And the rake db:migrate fails.

Perhaps the forem table could be prefixed with forem_ to namespace them?

http://edgeguides.rubyonrails.org/active_record_basics.html#overriding-the-naming-conventions

I am going to rename my table and models to work around this for now.

**Comment by radar** [comment] 2014-11-23 21:30
Forem does not have a subscriptions table. It creates a table called `forem_subscriptions` [as seen here](https://github.com/radar/forem/blob/074629e37a2712fb346657449250eaf6b9d39881/db/migrate/20111208014437_create_forem_subscriptions.rb).

The `subscriptions` table has likely come from your application.

If you can reproduce this within a new application, I would like to hear about it. For now, I am closing this issue as I believe it is caused by user error.

**Closed as completed by radar** 2014-11-23 21:30 UTC
