### ISSUE TITLE
uninitialized constant Forum 

### ISSUE THREAD

**Issue by danielres** [rubysherpas/forem#253] opened 2012-06-26 14:52 UTC
Hello

Just installed Forem on Rails 3.2.6.

I can see the forums list, I can enter the administration, manage forums and categories,...

But when I try to show a forum, I get an error:

``` ruby
NameError in Forem::ForumsController#show
uninitialized constant Forum
```

with:

``` ruby
Parameters:
{"id"=>"1"}
```

I tried with a blank app, same problem.

Any idea ?
Thanks

**Comment by hazg** [comment] 2012-06-26 15:43
cancan updated... 
gem 'cancan', '1.6.7' # can help you

**Comment by agarie** [comment] 2012-06-27 19:13
Using cancan 1.6.7 worked for me. Why is that? Could you explain? Thanks :)

**Comment by mmcc** [comment] 2012-06-27 19:39
+1 to both the issue and the solution.

**Comment by jasonlfunk** [comment] 2012-06-28 03:50
@agarie He meant that cancan updated to version 1.6.8 which broke Forem. If you force it to use 1.6.7, it works.

**Comment by agarie** [comment] 2012-06-28 04:21
@jasonlfunk Yes, it worked for me. Just wanted to know why it broke Forem. Thanks anyway!

**Comment by parndt** [comment] 2012-06-28 23:30
Often gems are released with backward incompatible changes in patch releases. We call these regressions and they're usually fixed once we let the author know of the problem who in this case is @ryanb :-)

Unless, of course, a bug was fixed in CanCan that we were relying on?

**Comment by radar** [comment] 2012-06-29 00:55
Can someone please provide a stacktrace for this issue? I'd be interested to know why this was broken.

**Comment by radar** [comment] 2012-06-29 04:56
Forem will now enforce CanCan 1.6.7 because 1.6.8 is broken. Will revise when necessary.

**Closed as completed by radar** 2012-06-29 04:56 UTC

**Comment by alexnesbitt** [comment] 2012-08-02 06:55
changing forums_controller.rb from
-load_and_authorize_resource  :only => :show
+load_and_authorize_resource :class => 'Forem::Forum', :only => :show

seems to fix this for cancan 1.6.8

I think this was the change from 1.6.7
https://github.com/ryanb/cancan/commit/d5baed6281b4628071f8737090eaaec5168eacbf

**Comment by parndt** [comment] 2012-08-02 07:02
Seems like the change should be reverted as this makes CanCan harder to use?

**Comment by radar** [comment] 2012-08-02 08:51
Namespaced controllers may not mean namespaced resources, such as in the case of `Admin::ForumsController`. I don't mind this CanCan change. 

If we need to upgrade to a later version of CanCan we can make the change as @alexnesbitt suggests.
