### ISSUE TITLE
post.user option

### ISSUE THREAD

**Issue by nordbit** [rubysherpas/forem#345] opened 2012-11-29 22:07 UTC
Can I define somewhere "post.user" ?
Because for now  "post.user" returns in view something like "#User:0x00000003cd78e8"
It should be cool option in initializer :
 : forem_user => :post.user.name 
or
:forem_user => post.user.email

**Comment by parndt** [comment] 2012-11-29 22:08
Duplicate of #344

**Closed as completed by parndt** 2012-11-29 22:08 UTC
