### ISSUE TITLE
installer fails

### ISSUE THREAD

**Issue by elado** [rubysherpas/forem#360] opened 2012-12-24 21:48 UTC
Had to run it twice since `forem_needs_moderation?` wasn't available for User.

```
✗ rails g forem:install

Copying over Forem migrations...
What is your user class called? [User] 
What is the current_user helper called in your app? [current_user] 
Defining forem_user method inside ApplicationController...
      insert  app/controllers/application_controller.rb
Adding forem initializer (config/initializers/forem.rb)...
      create  config/initializers/forem.rb
Running rake db:migrate
Creating default forum and topic
   (0.1ms)  BEGIN
  Forem::Category Load (9.4ms)  SELECT `forem_categories`.* FROM `forem_categories` WHERE (`slug` = 'general' OR `slug` LIKE 'general--%') ORDER BY LENGTH(`slug`) DESC, `slug` DESC LIMIT 1
  SQL (0.3ms)  INSERT INTO `forem_categories` (`created_at`, `name`, `slug`, `updated_at`) VALUES ('2012-12-24 21:05:28', 'General', 'general', '2012-12-24 21:05:28')
   (0.2ms)  COMMIT
  User Load (0.3ms)  SELECT `users`.* FROM `users` LIMIT 1
  Forem::Category Load (0.3ms)  SELECT `forem_categories`.* FROM `forem_categories` LIMIT 1
  Forem::Forum Load (0.2ms)  SELECT `forem_forums`.* FROM `forem_forums` WHERE `forem_forums`.`name` = 'Default' ORDER BY name ASC LIMIT 1
   (0.1ms)  BEGIN
  Forem::Forum Load (0.3ms)  SELECT `forem_forums`.* FROM `forem_forums` WHERE (`slug` = 'default' OR `slug` LIKE 'default--%') ORDER BY LENGTH(`slug`) DESC, `slug` DESC LIMIT 1
  Forem::Category Load (0.3ms)  SELECT `forem_categories`.* FROM `forem_categories` WHERE `forem_categories`.`id` = 1 LIMIT 1
  SQL (0.2ms)  INSERT INTO `forem_forums` (`category_id`, `description`, `name`, `slug`, `views_count`) VALUES (1, 'Default forem created by install', 'Default', 'default', 0)
   (0.2ms)  COMMIT
  Forem::Post Load (0.2ms)  SELECT `forem_posts`.* FROM `forem_posts` WHERE `forem_posts`.`text` = 'Hello World' LIMIT 1
  Forem::Topic Load (0.3ms)  SELECT `forem_topics`.* FROM `forem_topics` WHERE `forem_topics`.`subject` = 'Welcome to Forem' LIMIT 1
   (0.1ms)  BEGIN
  Forem::Topic Load (0.8ms)  SELECT `forem_topics`.* FROM `forem_topics` WHERE (`slug` = 'welcome-to-forem' OR `slug` LIKE 'welcome-to-forem--%') ORDER BY LENGTH(`slug`) DESC, `slug` DESC LIMIT 1
  SQL (0.3ms)  INSERT INTO `forem_topics` (`created_at`, `forum_id`, `hidden`, `last_post_at`, `locked`, `pinned`, `slug`, `state`, `subject`, `updated_at`, `user_id`, `views_count`) VALUES ('2012-12-24 21:05:28', 1, 0, NULL, 0, 0, 'welcome-to-forem', 'pending_review', 'Welcome to Forem', '2012-12-24 21:05:28', 1, 0)
  SQL (0.3ms)  INSERT INTO `forem_posts` (`created_at`, `notified`, `reply_to_id`, `state`, `text`, `topic_id`, `updated_at`, `user_id`) VALUES ('2012-12-24 21:05:28', 0, NULL, 'pending_review', 'Hello World', 1, '2012-12-24 21:05:28', 1)
  Forem::Topic Load (0.3ms)  SELECT `forem_topics`.* FROM `forem_topics` WHERE `forem_topics`.`id` = 1 LIMIT 1
  Forem::Post Load (0.3ms)  SELECT `forem_posts`.* FROM `forem_posts` WHERE `forem_posts`.`topic_id` = 1 ORDER BY forem_posts.created_at ASC LIMIT 1
  User Load (0.3ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1
   (0.7ms)  UPDATE `forem_topics` SET `last_post_at` = '2012-12-24 21:05:28', `updated_at` = '2012-12-24 21:05:28' WHERE `forem_topics`.`id` = 1
   (0.6ms)  ROLLBACK
~/.rvm/gems/ruby-1.9.3-p327/gems/activemodel-3.2.9/lib/active_model/attribute_methods.rb:407:in `method_missing': undefined method `forem_needs_moderation?' for #<User id=1 display_name=elado email=elado7@gmail.com> (NoMethodError)
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/attribute_methods.rb:149:in `method_missing'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.9/lib/active_support/core_ext/object/try.rb:36:in `try'
    from /blah/vendor/forem/app/models/forem/post.rb:116:in `skip_pending_review'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:417:in `_run__3550880709651814275__create__3498813176218642358__callbacks'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:405:in `__run_callback'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:385:in `_run_create_callbacks'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/callbacks.rb:268:in `create'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/persistence.rb:348:in `create_or_update'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/callbacks.rb:264:in `block in create_or_update'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:447:in `_run__3550880709651814275__save__3498813176218642358__callbacks'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:405:in `__run_callback'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/callbacks.rb:264:in `create_or_update'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/persistence.rb:84:in `save'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/validations.rb:50:in `save'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/attribute_methods/dirty.rb:22:in `save'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/transactions.rb:259:in `block (2 levels) in save'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/transactions.rb:208:in `transaction'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/transactions.rb:259:in `block in save'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/transactions.rb:270:in `rollback_active_record_state!'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/transactions.rb:258:in `save'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/associations/has_many_association.rb:16:in `insert_record'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/autosave_association.rb:346:in `block in save_collection_association'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/autosave_association.rb:337:in `each'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/autosave_association.rb:337:in `save_collection_association'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/autosave_association.rb:191:in `block in add_autosave_association_callbacks'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/autosave_association.rb:161:in `instance_eval'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/autosave_association.rb:161:in `block in define_non_cyclic_method'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:413:in `_run__3187117221731418145__create__3498813176218642358__callbacks'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:405:in `__run_callback'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:385:in `_run_create_callbacks'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/callbacks.rb:268:in `create'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/persistence.rb:348:in `create_or_update'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/callbacks.rb:264:in `block in create_or_update'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:458:in `_run__3187117221731418145__save__3498813176218642358__callbacks'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:405:in `__run_callback'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/callbacks.rb:264:in `create_or_update'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/persistence.rb:104:in `save!'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/validations.rb:56:in `save!'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/attribute_methods/dirty.rb:33:in `save!'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/transactions.rb:264:in `block in save!'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/transactions.rb:208:in `transaction'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.9/lib/active_record/transactions.rb:264:in `save!'
    from /blah/vendor/forem/db/seeds.rb:17:in `<top (required)>'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:245:in `load'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:245:in `block in load'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:236:in `load_dependency'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:245:in `load'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.9/lib/rails/engine.rb:520:in `load_seed'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.9/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /blah/vendor/forem/lib/generators/forem/install_generator.rb:67:in `seed_database'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/thor-0.16.0/lib/thor/task.rb:27:in `run'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/thor-0.16.0/lib/thor/invocation.rb:120:in `invoke_task'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/thor-0.16.0/lib/thor/invocation.rb:126:in `block in invoke_all'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/thor-0.16.0/lib/thor/invocation.rb:126:in `each'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/thor-0.16.0/lib/thor/invocation.rb:126:in `map'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/thor-0.16.0/lib/thor/invocation.rb:126:in `invoke_all'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/thor-0.16.0/lib/thor/group.rb:238:in `dispatch'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/thor-0.16.0/lib/thor/base.rb:425:in `start'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.9/lib/rails/generators.rb:171:in `invoke'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.9/lib/rails/commands/generate.rb:12:in `<top (required)>'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/backports-2.6.5/lib/backports/tools.rb:314:in `require'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/backports-2.6.5/lib/backports/tools.rb:314:in `require_with_backports'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:251:in `block in require'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:236:in `load_dependency'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:251:in `require'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/railties-3.2.9/lib/rails/commands.rb:29:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'


✗ rails g forem:install

Connecting to database specified by database.yml
Copying over Forem migrations...
What is your user class called? [User] 
What is the current_user helper called in your app? [current_user] 
Defining forem_user method inside ApplicationController...
      insert  app/controllers/application_controller.rb
Skipping config/initializers/forem.rb creation, as file already exists!
Running rake db:migrate
Creating default forum and topic
   (0.1ms)  BEGIN
  Forem::Category Load (3.8ms)  SELECT `forem_categories`.* FROM `forem_categories` WHERE (`slug` = 'general' OR `slug` LIKE 'general--%') ORDER BY LENGTH(`slug`) DESC, `slug` DESC LIMIT 1
  SQL (0.9ms)  INSERT INTO `forem_categories` (`created_at`, `name`, `slug`, `updated_at`) VALUES ('2012-12-24 21:41:26', 'General', 'general--2', '2012-12-24 21:41:26')
   (52.8ms)  COMMIT
  User Load (0.4ms)  SELECT `users`.* FROM `users` LIMIT 1
  Forem::Category Load (0.4ms)  SELECT `forem_categories`.* FROM `forem_categories` LIMIT 1
  Forem::Forum Load (0.2ms)  SELECT `forem_forums`.* FROM `forem_forums` WHERE `forem_forums`.`name` = 'Default' ORDER BY name ASC LIMIT 1
  Forem::Post Load (0.2ms)  SELECT `forem_posts`.* FROM `forem_posts` WHERE `forem_posts`.`text` = 'Hello World' LIMIT 1
  Forem::Topic Load (0.2ms)  SELECT `forem_topics`.* FROM `forem_topics` WHERE `forem_topics`.`subject` = 'Welcome to Forem' LIMIT 1
   (0.1ms)  BEGIN
  Forem::Topic Load (0.3ms)  SELECT `forem_topics`.* FROM `forem_topics` WHERE (`slug` = 'welcome-to-forem' OR `slug` LIKE 'welcome-to-forem--%') ORDER BY LENGTH(`slug`) DESC, `slug` DESC LIMIT 1
  SQL (0.6ms)  INSERT INTO `forem_topics` (`created_at`, `forum_id`, `hidden`, `last_post_at`, `locked`, `pinned`, `slug`, `state`, `subject`, `updated_at`, `user_id`, `views_count`) VALUES ('2012-12-24 21:41:27', 1, 0, NULL, 0, 0, 'welcome-to-forem', 'pending_review', 'Welcome to Forem', '2012-12-24 21:41:27', 1, 0)
  SQL (0.1ms)  INSERT INTO `forem_posts` (`created_at`, `notified`, `reply_to_id`, `state`, `text`, `topic_id`, `updated_at`, `user_id`) VALUES ('2012-12-24 21:41:27', 0, NULL, 'pending_review', 'Hello World', 2, '2012-12-24 21:41:27', 1)
  Forem::Topic Load (0.3ms)  SELECT `forem_topics`.* FROM `forem_topics` WHERE `forem_topics`.`id` = 2 LIMIT 1
  Forem::Post Load (0.2ms)  SELECT `forem_posts`.* FROM `forem_posts` WHERE `forem_posts`.`topic_id` = 2 ORDER BY forem_posts.created_at ASC LIMIT 1
  User Load (0.2ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1
   (0.4ms)  UPDATE `forem_topics` SET `last_post_at` = '2012-12-24 21:41:27', `updated_at` = '2012-12-24 21:41:27' WHERE `forem_topics`.`id` = 2
  Forem::Subscription Exists (0.3ms)  SELECT 1 AS one FROM `forem_subscriptions` WHERE `forem_subscriptions`.`topic_id` = 2 AND `forem_subscriptions`.`subscriber_id` = 1 LIMIT 1
  SQL (0.2ms)  INSERT INTO `forem_subscriptions` (`subscriber_id`, `topic_id`) VALUES (1, 2)
   (0.2ms)  COMMIT
Mounting Forem::Engine at "/forums" in config/routes.rb...
      insert  config/routes.rb


*****************************************************
Done! Forem has been successfully installed. Yaaaaay!

Here's what happened:

1) Forem's migrations were copied over into db/migrate.

2) We created a new migration called AddForemAdminToTable.
   This creates a new field called "forem_admin" on your User model's table.

3) A new method called `forem_user` was inserted into your ApplicationController.
   This lets Forem know what the current user of your application is.

4) A new file was created at config/initializers/forem.rb
   This is where you put Forem's configuration settings.

5) `rake db:migrate` was run, running all the migrations against your database.

6) Seed forum and topic were loaded into your database.

7) The engine was mounted in your config/routes.rb file using this line:

   mount Forem::Engine, :at => "/forums"

   If you want to change where the forums are located, just change the "/forums" path at the end of this line to whatever you want.

And finally:

8) We told you that Forem has been successfully installed and walked you through the steps.

If you have any questions, comments or issues, please post them on our issues page: http://github.com/radar/forem/issues.

Thanks for using Forem!
```

**Comment by radar** [comment] 2012-12-28 04:32
This issue is a duplicate of the one in #343. Let's keep the discussion going on there.

**Closed as completed by radar** 2012-12-28 04:32 UTC
