### ISSUE TITLE
How to access Forem routes outside of engine

### ISSUE THREAD

**Issue by murtazajafferji** [rubysherpas/forem#274] opened 2012-08-01 00:32 UTC
How do I use Forem url helpers outside of the engine in my main app? I get this error:

<code>undefined local variable or method `forums_path' for #<#Class:0x007fa1890db268:0x007fa1890b6260>
Extracted source (around line #2):
2:   <%= link_to t('forem.forum.forums'), forums_path %> &raquo; <%= link_to forum.category, forum.category %> &raquo; <%= link_to forum.title, forum %>
</code>

I have tried changing it to forums.forums_path, but that didn't work.

**Comment by parndt** [comment] 2012-08-01 00:34
Try forem.forums_path

**Comment by murtazajafferji** [comment] 2012-08-01 01:06
The reason why I thought forums.forums_path would work is because of this line in routes.rb:
<code>mount Forem::Engine, :at => "/forums"</code>

Anyways, I got this error when trying forem.forums_path:
<code>undefined method `forums_path' for #<#Class:0x007fa1890db268:0x007fa187a7e830>
Extracted source (around line #2):
2:   <%= link_to t('forem.forum.forums'), forem.forums_path %> &raquo; <%= link_to forum.category, forum.category %> &raquo; <%= link_to forum.title, forum %></code>

**Comment by radar** [comment] 2012-08-01 01:53
You should be using `forem.forums_path`. The engine's name is forem.

See the [Engines Guide](http://guides.rubyonrails.org/engines.html)

**Comment by murtazajafferji** [comment] 2012-08-01 03:27
In my last comment, I provided the error that occurs when I use <code>forem.forums_path</code>. Is there something else I should be doing?

**Comment by murtazajafferji** [comment] 2012-08-01 05:15
Do you think it has something to do with the fact that I am calling the url helpers inside of the Spree engine?

**Comment by radar** [comment] 2012-08-01 05:21
Calling the helpers inside Spree will be fine as long as you use the prefix. If you don't use the prefix then you will be having this problem. 

If you can duplicate the error in a brand new Rails app I can take a look at it once I am out of this traffic. 

## 

Ryan Bigg

**Comment by murtazajafferji** [comment] 2012-08-01 06:42
ok great. I just created a new app with Spree and Forem and I reproduced the issue:
https://github.com/murtazajafferji/forem_url_helpers_demo

**Comment by radar** [comment] 2012-08-01 06:42
Where in this application are you seeing the error?

**Comment by murtazajafferji** [comment] 2012-08-01 06:45
home#test. I set it up as the root.

**Comment by radar** [comment] 2012-08-01 06:52
The application is broken because `sign_in_path` is not defined.

**Comment by murtazajafferji** [comment] 2012-08-01 06:56
I added you as a collaborator. Do you mind pushing your fix up?

Also, in that test app, I did not include this line that is in my original app:
<code>mount Forem::Engine, :at => "/forums"</code>

Is this line necessary?

**Comment by parndt** [comment] 2012-08-01 06:59
Yeah that line is 100% essential for _any_ forem routes to work.

**Comment by radar** [comment] 2012-08-01 07:03
Please provide an application that can reproduce this error quickly. As much as I enjoy hearing about people using Forem and _actually_ using it, I do not have the time to come up with example applications on my own. Please help us, help you.

**Comment by murtazajafferji** [comment] 2012-08-01 07:10
I just pushed up the application with <code>mount Forem::Engine, :at => "/forums"</code> added to <code>routes.rb</code>.

This error will come up when you start the app because of the line where I have the path <code>forem.forums_path</code>:
<code>No route matches {:controller=>"spree/home", :action=>"test"}</code>

**Comment by radar** [comment] 2012-08-01 07:34
Ok, now I see the problem. It's because we weren't prefixing all URLs inside of Forem with `forem.` as we should have been doing. I've now fixed this with @dd993982f2470317f9adc14b6eb27a24d2f95fbf. Please try out that commit and see how you go.

**Closed as completed by radar** 2012-08-01 07:34 UTC

**Comment by radar** [comment] 2012-08-01 07:35
Whoops, just need to fix some conflicts and then I can push. one moment.

**Comment by radar** [comment] 2012-08-01 07:37
Ok, dd993982f2470317f9adc14b6eb27a24d2f95fbf is the commit. Please try it out. Thanks for taking the time to provide that application. It really helped!

**Comment by parndt** [comment] 2012-08-01 07:40
Wow how did our tests not notice?

**Comment by radar** [comment] 2012-08-01 07:45
Because our tests are isolated and we're not including any partial into the main app of our test suite. Someone should really write a test for that.

**Comment by parndt** [comment] 2012-08-01 07:46
Someone should.

**Comment by murtazajafferji** [comment] 2012-08-01 08:06
Thanks guys! It works!!!
