### ISSUE TITLE
?locale= appended to the end of URLs

### ISSUE THREAD

**Issue by dalvallana** [rubysherpas/forem#641] opened 2015-02-19 16:41 UTC
I followed I18n rails' guidelines to add locale param at the beginning of a url, like `http://localhost/en/forem`. It works fine, but for some reason, only for the forem engine, besides the "en" at the beginning of the url, a `?locale=en` is appended to the end. What's going on here?

**Comment by radar** [comment] 2015-02-20 22:39
@daao87 Please provide steps to reproduce this problem in a new application.

**Comment by radar** [comment] 2015-05-26 22:52
No steps have been provided, so I am now closing this issue.

**Closed as completed by radar** 2015-05-26 22:52 UTC

**Comment by yan-hoose** [comment] 2015-06-21 13:52
I ran into the same issue. Here is a small app that reproduces this: https://github.com/yan-hoose/forem-locale-issue

Basically since the URL inside Forem becomes something like http://localhost:3000/de/forums/categories/general?locale=de and this makes changing the locale while looking at Forem views difficult since it only changes the last locale param.

It seems that this is caused by the locale scope not broadening on to engine routes. If you look at the output of `bin/rake routes`, you'll see that Forem does not have the locale scope.
