### ISSUE TITLE
Devise sign in route

### ISSUE THREAD

**Issue by avitus** [rubysherpas/forem#202] opened 2012-04-19 22:34 UTC
More of a comment than an issue:

In application_controller.rb:

  def authenticate_forem_user 
      ...
      redirect_to main_app.sign_in_path
      ...
  end

Is 'sign_in_path' a standard devise route? I saw in the Heroku version of the app you added:

match '/users/sign_in', :to => "devise/sessions#new", :as => "sign_in"

This worked for me too but might be better to just use new_user_session_path since that seems to be default in Devise.

**Comment by knewter** [comment] 2012-04-23 05:15
It's also conceivable that we would want to make this path configurable and just default it to sign_in_path or new_user_session_path - either way, it needs to be documented that we expect the main_app to have that route defined.

**Comment by knewter** [comment] 2012-04-24 20:50
This is now configurable per the above merged commit, so closing the issue.

**Closed as completed by knewter** 2012-04-24 20:50 UTC

**Comment by mbhnyc** [comment] 2012-08-09 15:32
Odd, i'm getting an "undefined local variable or method `main_app'" error when assigning a custom sign_in_path in the initializer — anyone else seeing this?

My init line looks like:

```
Forem.sign_in_path = main_app.new_provider_session_path
```

**Comment by radar** [comment] 2012-08-09 21:39
You can't reference main_app inside an initializer.  

## 

Ryan Bigg

**Comment by mbhnyc** [comment] 2012-08-10 05:32
So I tried both ways, and now have done a little more testing.

When i'm logged in, I can visit the Create Topic page, works great.

When i'm logged OUT, visiting the Create Topic page gives me the exception, which makes sense as you must be logged in to create a topic, having looked at the controller, I see authentication should be occurring, but it seems to be getting confused somehow...it shouldn't even get to the rendering step.

Here's the full error:

```
NoMethodError in Forem::TopicsController#new
undefined method `sign_in_path' for #<ActionDispatch::Routing::RoutesProxy:0x007fd8e3f4e6d8>
```

Is the authorize! method not picking up that my user model is renamed?  Hrm.. will have to look more closely..

**Comment by radar** [comment] 2012-08-10 05:37
@mbhnyc: Please provide us with an application that reproduces the issue that you're seeing.

**Comment by mbhnyc** [comment] 2012-08-10 06:20
Here you go:

https://github.com/mbhnyc/forem_test

Steps to re-create (kind of a pain, trying to keep it basic!):

1) go to /providers/sign_up, create account
2) make account an admin in console
3) go to /forums and create a test forum
4) open http://0.0.0.0:3000/forums/forums/test, you should correctly see a "New Topic" link
5) open another browser and open page from 4, you should NOT see a "New Topic" link **as you're logged out**.
6) There's a New Topic link there anyway, clicking it will give the error above.

**Comment by radar** [comment] 2012-08-10 06:39
Hm, I wonder why that problem hasn't come up sooner than this. I will look at crafting a patch to make this work now.

**Comment by mbhnyc** [comment] 2012-08-10 06:41
Curious about the solution, as the controller looks to be checking login state correctly at first read.  yay fixing things!

**Comment by radar** [comment] 2012-08-10 06:56
It is checking the login state correctly... that's not the problem. The problem is that it's attempting to go to a `sign_in_path` route for your application which is not defined. But you're using Devise, and since that's the _de facto_ auth system these days and it provides its own routes, we should at least attempt to see if we can guess Devise's routes before erroring out. 

And then when we error out we should do so in a much more informative manner.

**Comment by radar** [comment] 2012-08-10 07:05
Check out @01a6623 and see if that helps you.
