### ISSUE TITLE
undefined local variable or method `per'

### ISSUE THREAD

**Issue by frankel** [rubysherpas/forem#38] opened 2011-09-07 04:27 UTC
When I acces "http://localhost/forem/forums/1", it throws the error message of " undefined local variable or method `per' ". 

It occurs at app/controllers/forem/forums_controller.rb:11:in `show'  : 

@forum.topics.visible.by_pinned_or_most_recent_post.page(params[:page]).per(20)

I don't know what this per method is. Do I miss any gem?

**Comment by parndt** [comment] 2011-09-07 04:28
Seems to do with pagination, specifically kaminari which is a runtime dependency of forem.

**Comment by radar** [comment] 2011-09-07 04:28
Could you provide the stacktrace for this error please? This should be provided by the Kaminari gem. I would think if per were failing then page would fail too.

**Comment by frankel** [comment] 2011-09-07 04:29
@radar. Here is the stacktrace: 

activerecord (3.1.0) lib/active_record/relation.rb:459:in `method_missing'
/home/frankel/.rvm/gems/ruby-1.9.2-p180/bundler/gems/forem-9e311b2fe76c/app/controllers/forem/forums_controller.rb:11:in`show'
actionpack (3.1.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (3.1.0) lib/abstract_controller/base.rb:167:in`process_action'
actionpack (3.1.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (3.1.0) lib/abstract_controller/callbacks.rb:18:in`block in process_action'
activesupport (3.1.0) lib/active_support/callbacks.rb:434:in `_run__2876209848409916127__process_action__3573239026572013727__callbacks'
activesupport (3.1.0) lib/active_support/callbacks.rb:386:in`_run_process_action_callbacks'
activesupport (3.1.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.1.0) lib/abstract_controller/callbacks.rb:17:in`process_action'
actionpack (3.1.0) lib/action_controller/metal/rescue.rb:17:in `process_action'
actionpack (3.1.0) lib/action_controller/metal/instrumentation.rb:30:in`block in process_action'
activesupport (3.1.0) lib/active_support/notifications.rb:53:in `block in instrument'
activesupport (3.1.0) lib/active_support/notifications/instrumenter.rb:21:in`instrument'
activesupport (3.1.0) lib/active_support/notifications.rb:53:in `instrument'
actionpack (3.1.0) lib/action_controller/metal/instrumentation.rb:29:in`process_action'
actionpack (3.1.0) lib/action_controller/metal/params_wrapper.rb:201:in `process_action'
activerecord (3.1.0) lib/active_record/railties/controller_runtime.rb:18:in`process_action'
actionpack (3.1.0) lib/abstract_controller/base.rb:121:in `process'
actionpack (3.1.0) lib/abstract_controller/rendering.rb:45:in`process'
actionpack (3.1.0) lib/action_controller/metal.rb:193:in `dispatch'
actionpack (3.1.0) lib/action_controller/metal/rack_delegation.rb:14:in`dispatch'
actionpack (3.1.0) lib/action_controller/metal.rb:236:in `block in action'
actionpack (3.1.0) lib/action_dispatch/routing/route_set.rb:65:in`call'
actionpack (3.1.0) lib/action_dispatch/routing/route_set.rb:65:in `dispatch'
actionpack (3.1.0) lib/action_dispatch/routing/route_set.rb:29:in`call'
rack-mount (0.8.3) lib/rack/mount/route_set.rb:152:in `block in call'
rack-mount (0.8.3) lib/rack/mount/code_generation.rb:96:in`block in recognize'
rack-mount (0.8.3) lib/rack/mount/code_generation.rb:103:in `optimized_each'
rack-mount (0.8.3) lib/rack/mount/code_generation.rb:95:in`recognize'
rack-mount (0.8.3) lib/rack/mount/route_set.rb:141:in `call'
actionpack (3.1.0) lib/action_dispatch/routing/route_set.rb:531:in`call'
railties (3.1.0) lib/rails/engine.rb:455:in `call'
railties (3.1.0) lib/rails/railtie/configurable.rb:30:in`method_missing'
rack-mount (0.8.3) lib/rack/mount/prefix.rb:26:in `call'
rack-mount (0.8.3) lib/rack/mount/route_set.rb:152:in`block in call'
rack-mount (0.8.3) lib/rack/mount/code_generation.rb:96:in `block in recognize'
rack-mount (0.8.3) lib/rack/mount/code_generation.rb:75:in`optimized_each'
rack-mount (0.8.3) lib/rack/mount/code_generation.rb:95:in `recognize'
rack-mount (0.8.3) lib/rack/mount/route_set.rb:141:in`call'
actionpack (3.1.0) lib/action_dispatch/routing/route_set.rb:531:in `call'
warden (1.0.5) lib/warden/manager.rb:35:in`block in call'
warden (1.0.5) lib/warden/manager.rb:34:in `catch'
warden (1.0.5) lib/warden/manager.rb:34:in`call'
actionpack (3.1.0) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
rack (1.3.2) lib/rack/etag.rb:23:in`call'
rack (1.3.2) lib/rack/conditionalget.rb:25:in `call'
actionpack (3.1.0) lib/action_dispatch/middleware/head.rb:14:in`call'
actionpack (3.1.0) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.1.0) lib/action_dispatch/middleware/flash.rb:243:in`call'
rack (1.3.2) lib/rack/session/abstract/id.rb:195:in `context'
rack (1.3.2) lib/rack/session/abstract/id.rb:190:in`call'
actionpack (3.1.0) lib/action_dispatch/middleware/cookies.rb:326:in `call'
activerecord (3.1.0) lib/active_record/query_cache.rb:62:in`call'
activerecord (3.1.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:477:in `call'
actionpack (3.1.0) lib/action_dispatch/middleware/callbacks.rb:29:in`block in call'
activesupport (3.1.0) lib/active_support/callbacks.rb:392:in `_run_call_callbacks'
activesupport (3.1.0) lib/active_support/callbacks.rb:81:in`run_callbacks'
actionpack (3.1.0) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
actionpack (3.1.0) lib/action_dispatch/middleware/reloader.rb:68:in`call'
rack (1.3.2) lib/rack/sendfile.rb:101:in `call'
actionpack (3.1.0) lib/action_dispatch/middleware/remote_ip.rb:48:in`call'
actionpack (3.1.0) lib/action_dispatch/middleware/show_exceptions.rb:47:in `call'
railties (3.1.0) lib/rails/rack/logger.rb:13:in`call'
rack (1.3.2) lib/rack/methodoverride.rb:24:in `call'
rack (1.3.2) lib/rack/runtime.rb:17:in`call'
dragonfly (0.9.5) lib/dragonfly/middleware.rb:13:in `call'
rack-cache (1.0.3) lib/rack/cache/context.rb:132:in`forward'
rack-cache (1.0.3) lib/rack/cache/context.rb:243:in `fetch'
rack-cache (1.0.3) lib/rack/cache/context.rb:181:in`lookup'
rack-cache (1.0.3) lib/rack/cache/context.rb:65:in `call!'
rack-cache (1.0.3) lib/rack/cache/context.rb:50:in`call'
dragonfly (0.9.5) lib/dragonfly/middleware.rb:13:in `call'
rack-cache (1.0.3) lib/rack/cache/context.rb:132:in`forward'
rack-cache (1.0.3) lib/rack/cache/context.rb:243:in `fetch'
rack-cache (1.0.3) lib/rack/cache/context.rb:181:in`lookup'
rack-cache (1.0.3) lib/rack/cache/context.rb:65:in `call!'
rack-cache (1.0.3) lib/rack/cache/context.rb:50:in`call'
rack (1.3.2) lib/rack/lock.rb:15:in `call'
actionpack (3.1.0) lib/action_dispatch/middleware/static.rb:53:in`call'
dragonfly (0.9.5) lib/dragonfly/cookie_monster.rb:9:in `call'
railties (3.1.0) lib/rails/engine.rb:455:in`call'
railties (3.1.0) lib/rails/rack/content_length.rb:16:in `call'
railties (3.1.0) lib/rails/rack/log_tailer.rb:14:in`call'
rack (1.3.2) lib/rack/handler/webrick.rb:59:in `service'
/home/frankel/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/webrick/httpserver.rb:111:in`service'
/home/frankel/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/webrick/httpserver.rb:70:in `run'
/home/frankel/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/webrick/server.rb:183:in`block in start_thread'

**Comment by radar** [comment] 2011-09-07 04:33
@frankel: and to confirm, bundle list contains the kaminari gem?

**Comment by frankel** [comment] 2011-09-07 04:36
@radar, yeah, with kaminari (0.12.4)

**Comment by frankel** [comment] 2011-09-07 04:51
btw, my gemfile is:

source 'http://rubygems.org'

gem 'rails', '3.1.0'

gem 'sqlite3'

gem 'refinerycms', :git => 'https://github.com/resolve/refinerycms.git'

gem 'arel', :git => "git://github.com/rails/arel.git"
gem 'sprockets', :git => "git://github.com/sstephenson/sprockets.git"
gem 'forem', :git => "git://github.com/radar/forem.git"
gem 'forem-theme-base', :git => "git://github.com/radar/forem-theme-base"

group :assets do
  gem 'sass-rails', "  ~> 3.1.0"
  gem 'coffee-rails', "~> 3.1.0"
  gem 'uglifier'
end

gem 'jquery-rails'

gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end

**Comment by radar** [comment] 2011-09-07 05:11
Ah, that's quite the fun one :) It's happening because `will_paginate` 3.0 (a dependency of Refinery) now defines its own `page` method, and so it's calling that one, rather than the Kaminari one which Forem asks for. I can take a further look at this tonight. Sorry for not catching it earlier.

**Comment by parndt** [comment] 2011-09-07 05:12
Like you could have caught it earlier!

**Comment by radar** [comment] 2011-09-07 05:17
Well, if I had updated the forem Heroku demo version like I have as a TODO on The Wall at home on the weekend like I had planned to, instead of going OUTSIDE, then yes, I would have caught it then :) See kiddos, this is why you shouldn't go away from the computer!

**Comment by parndt** [comment] 2011-09-07 05:18
You can see better with square eyes anyway, right?

**Comment by frankel** [comment] 2011-09-07 05:19
Thanks radar and parndt. Waiting for your update:)

**Comment by radar** [comment] 2011-09-07 22:45
What happens when you `include Kaminari::ActiveRecordExtension` into the Post model? Does that fix this? It's a bit of a hack :\

**Comment by frankel** [comment] 2011-09-08 01:09
Tried, and still not work...

**Comment by radar** [comment] 2011-09-08 01:10
Alright then. I can look again tonight after work. Stupid `will_paginate`.

**Comment by frankel** [comment] 2011-09-08 02:54
I applied the initialize code in kaminari (railtie.rb) to forem initializing if will_paginate is found, but it failed again.

**Comment by radar** [comment] 2011-09-08 03:34
I attempted to fix this at the end of my lunch break to no avail. I will look again further tonight. I suspect it may require patches to `will_paginate`.

**Comment by wakeless** [comment] 2011-09-08 04:49
The main problem seems to be caused by the fact that the Kaminari loads itself into ActiveRecord WHEN you call page

https://github.com/amatsuda/kaminari/blob/master/lib/kaminari/models/active_record_model_extension.rb#L12

I suspect if you include 
     include Kaminari::ActiveRecordRelationMethods
     include Kaminari::PageScopeMethods

into the relation it _might_ work

**Comment by radar** [comment] 2011-09-08 23:29
I tried this without luck:

```
if defined?(WillPaginate) && defined?(Kaminari)
  class Forem::Post < ActiveRecord::Base
    include Kaminari::ActiveRecordRelationMethods
    include Kaminari::PageScopeMethods
  end
end
```

**Comment by cobalamin** [comment] 2011-09-09 21:31
What about defining a "page" method as a helper for that controller that will call the Kaminari page method? IDK if this makes any sense at the moment...

**Comment by radar** [comment] 2011-09-10 00:22
OK, I reckon I've got this nutted out now. When you call the `page` method, WillPaginate creates a new scope using `rel.scoped` (i.e. `Model.scoped`) and then extends that like this: https://github.com/mislav/will_paginate/blob/master/lib/will_paginate/active_record.rb#L136. This module is defined at the top of the file: https://github.com/mislav/will_paginate/blob/master/lib/will_paginate/active_record.rb#L20-28.

It contains a method called `per_page` when the Kaminari alternative is called `page`. So it's a simple fix for this issue, alias the method `per` to `per_page` if `WillPaginate` is defined.

Next, we use `num_pages` in Forem to determine how many topics there are. If there is more than one page of topics then we display a pagination limit. The `num_pages` method is again from Kaminari and so when `WillPaginate` is defined we need to define `total_pages` for this also.

Both of these methods we add to the `WillPaginate::ActiveRecord::RelationMethods` module so it's compatible.

The final thing to do is to use the `will_paginate` method if `WillPaginate` is defined, or use `paginate` which is provided by Kaminari as the "fallback". As such, I've defined a `forem_paginate` method that does this. Since the API for the two methods are basically the same (at least they are for our purposes), I don't see any problem with this solution.

Please review my commit `a066a5b` and provide feedback. 

Thank you.

**Comment by radar** [comment] 2011-09-10 00:24
Also 46ea7d2, but that's trivial really.

**Comment by knewter** [comment] 2011-09-10 05:39
refinery master's using will_paginate again?  I didn't realize.  Anyway, nice to have forem work with apps using will_paginate I guess :)  I would think that there'd be some value in one or both of those gems doing something like this to resolve conflicts right?

**Comment by parndt** [comment] 2011-09-10 05:40
Yea, it really would.

**Comment by radar** [comment] 2011-09-10 08:05
It would be _super nice_ if these two gems had _identical_ APIs, but unfortunately they both have divergent ideas of what the API for pagination should be. If these two libraries had the same API then what would be the point of having two libraries besides _possible_ performance improvements?

Currently, we don't use anything _too_ intense in forem and so the "hacks" in my commits earlier today I think are fine.

**Comment by wakeless** [comment] 2011-09-10 08:12
If they had exactly the same API they'd conflict even worse. The problem is
where the API overlap.

On Sat, Sep 10, 2011 at 6:05 PM, Ryan Bigg <
reply@reply.github.com>wrote:

> It would be _super nice_ if these two gems had _identical_ APIs, but
> unfortunately they both have divergent ideas of what the API for pagination
> should be. If these two libraries had the same API then what would be the
> point of having two libraries besides _possible_ performance improvements?
> 
> Currently, we don't use anything _too_ intense in forem and so the "hacks"
> in my commits earlier today I think are fine.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/radar/forem/issues/38#issuecomment-2058413

## 

Checkout my new website: http://myachinghead.net
http://wakeless.net

**Comment by frankel** [comment] 2011-09-10 09:01
It works fine! Thanks @radar!

**Closed as completed** 2011-09-10 10:00 UTC
