### ISSUE TITLE
Email notifications not sending in production 

### ISSUE THREAD

**Issue by lyneux** [rubysherpas/forem#604] opened 2014-09-25 14:58 UTC
I'm tearing my hair out with this one:

1) Email notifications work in development.
2) Production has exactly the same action_mailer configuration (I'm using OpenShift in production BTW).
3) I know that action_mailer works ok in production because I have other code (password reset functionality) that uses it and I receive emails ok from that code.
4) Switching log_level to debug shows that topic_reply.text.erb is not being rendered in production but is being rendered in development.
5) The production database is an exact copy of the development database (dump/restore) and I am following the same steps (same exact forum) to test the notifications (replying using user2 to a topic that is subscribed by user1).

Any suggestions on how to proceed?

Many thanks,

Guy

**Comment by lyneux** [comment] 2014-09-25 15:04
Also, I have in my production.rb:

config.action_mailer.raise_delivery_errors = true

I think this rules out a problem with the mailer?

**Comment by bodrovis** [comment] 2014-09-25 15:06
@lyneux Do you see any errors in the logs?

**Comment by lyneux** [comment] 2014-09-25 15:34
No, nothing. The PostsController redirects straight back to the topic:

```
Started POST "/forums/announcements/topics/2014-calendars/posts" for 127.5.98.1 at 2014-09-25 09:15:50 -0400
Processing by Forem::PostsController#create as HTML
Parameters: {"utf8"=>"✓", "authenticity_token"=>"ZXCJvo+WxlnZxrEprCX8FFq2SCjxBeB7Qpb8G8Ks6XY=", "post"=>{"text"=>"test8", "reply_to_id"=>"36125"}, "commit"=>"Post Reply", "forum_id"=>"announcements", "topic_id"=>"2014-calendars"}
Redirected to http://membership-lmc.rhcloud.com/forums/announcements/topics/2014-calendars?page=1
```

**Comment by lyneux** [comment] 2014-10-31 12:31
Bump - anyone any ideas on how to proceed with debugging this? I am running production on Redhat Openshift.

**Comment by radar** [comment] 2014-11-03 00:12
@lyneux It's hard for us to debug this without access to the production server. Sorry!`

**Comment by pavankat** [comment] 2015-02-24 05:32
@lyneux What are you using for your email notifications? Mandrill? You can set your rails app to production mode and put a binding.pry right after the email gets sent in the controller.

**Comment by dt1973** [comment] 2015-02-24 06:28
Could also set up a live test case via http://runnable.com/.

**Comment by radar** [comment] 2015-07-13 22:23
Closing due to age and that there hasn't been a reproducible example provided.

**Closed as completed by radar** 2015-07-13 22:23 UTC
